### ISSUE TITLE
plugin not work

### ISSUE THREAD

**Issue by DimaSergeew** [Franc1es/BetterDuels#3]
[19:17:52] [Server thread/ERROR]: Error occurred while enabling BetterDuels v1.2.1 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:251) ~[BetterDuels-1.2.1.jar:?]
	at org.bstats.MetricsBase.<init>(MetricsBase.java:121) ~[BetterDuels-1.2.1.jar:?]
	at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[BetterDuels-1.2.1.jar:?]
	at dev.francies.betterduels.BetterDuels.onEnable(BetterDuels.java:47) ~[BetterDuels-1.2.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[?:git-UniverseSpigot-"af46338"]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[?:git-UniverseSpigot-"af46338"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[?:git-UniverseSpigot-"af46338"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[?:git-UniverseSpigot-"af46338"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:642) ~[?:git-UniverseSpigot-"af46338"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:553) ~[?:git-UniverseSpigot-"af46338"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[?:git-UniverseSpigot-"af46338"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[?:git-UniverseSpigot-"af46338"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[?:git-UniverseSpigot-"af46338"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Franc1es** [comment]
Hi, I'm working on it, probably bStats wasn't shaded properly.

Il mar 24 set 2024, 18:20 Vadim Naumenko ***@***.***> ha
scritto:

**Comment by Franc1es** [comment]
I have released a new version with some fixes and new features
